In [ ]:
grid=[[5,3,0,0,7,0,0,0,0],
      [6,0,0,1,9,5,0,0,0],
      [0,9,8,0,0,0,0,6,0],
      [8,0,0,0,6,0,0,0,3],
      [4,0,0,8,0,3,0,0,1],
      [7,0,0,0,2,0,0,0,6],
      [0,6,0,0,0,0,2,8,0],
      [0,0,0,4,1,9,0,0,5],
      [0,0,0,0,8,0,0,7,9]]
    

In [4]:
grid

[[5, 3, 0, 0, 7, 0, 0, 0, 0],
 [6, 0, 0, 1, 9, 5, 0, 0, 0],
 [0, 9, 8, 0, 0, 0, 0, 6, 0],
 [8, 0, 0, 0, 6, 0, 0, 0, 3],
 [4, 0, 0, 8, 0, 3, 0, 0, 1],
 [7, 0, 0, 0, 2, 0, 0, 0, 6],
 [0, 6, 0, 0, 0, 0, 2, 8, 0],
 [0, 0, 0, 4, 1, 9, 0, 0, 5],
 [0, 0, 0, 0, 8, 0, 0, 7, 9]]

In [5]:
import numpy as np

In [6]:
print(np.matrix(grid))

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]


In [41]:
def allowed (grid,y,x,guess):
    for i in range(9): 
        if grid[y][i]==guess or grid[i][x]==guess: return False
    for i in range(3):
        for j in range (3):
            if grid[y//3*3+i][x//3*3+j]==guess: return False
    return True
            
    

In [42]:
solve(grid)
    

[[3 4 5 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [5 3 4 2 8 6 1 7 9]]

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]



In [37]:
import numpy as np
def solve(grid):
    for y in range(9): 
        for x in range(9):
            if grid[y][x]==0: 
                for guess in range(1,10):
                    if allowed(grid,y,x,guess): 
                        grid[y][x]=guess
                        solve(grid)
                        grid[y][x]=0
                return
    print(np.matrix(grid));print

In [28]:
grid=[[5,3,0,0,7,0,0,0,0],
      [6,0,0,1,9,5,0,0,0],
      [0,9,8,0,0,0,0,6,0],
      [8,0,0,0,6,0,0,0,3],
      [4,0,0,8,0,3,0,0,1],
      [7,0,0,0,2,0,0,0,6],
      [0,6,0,0,0,0,2,8,0],
      [0,0,0,4,1,9,0,0,5],
      [0,0,0,0,8,0,0,7,9]]

In [38]:
solve(grid)

[[3 4 5 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [5 3 4 2 8 6 1 7 9]]

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]



In [17]:
grid=[[5,3,0,0,7,0,0,0,0],
      [6,0,0,1,9,5,0,0,0],
      [0,9,8,0,0,0,0,6,0],
      [8,0,0,0,6,0,0,0,3],
      [4,0,0,8,0,3,0,0,1],
      [7,0,0,0,2,0,0,0,6],
      [0,6,0,0,0,0,2,8,0],
      [0,0,0,4,1,9,0,0,5],
      [0,0,0,0,8,0,0,0,0]]

In [20]:
solve(grid)

[[5 3 4 6 7 8 1 9 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 9 7 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 7 1 9]]

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]



In [30]:
grid=[[0,0,0,0,0,0,0,0,0],
      [6,0,0,1,9,5,0,0,0],
      [0,9,8,0,0,0,0,6,0],
      [8,0,0,0,6,0,0,0,3],
      [4,0,0,8,0,3,0,0,1],
      [7,0,0,0,2,0,0,0,6],
      [0,6,0,0,0,0,2,8,0],
      [0,0,0,4,1,9,0,0,5],
      [0,0,0,0,8,0,0,7,9]]
    

In [31]:
solve(grid)

[[3 4 5 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [5 3 4 2 8 6 1 7 9]]

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]



In [21]:
import requests

In [25]:
page = requests.get("https://nine.websudoku.com/?set_id=610926282")

In [26]:
page

<Response [200]>

In [33]:
range(9)

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [34]:
range(0,9)

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [27]:
page.content

'<HTML>\n\t<HEAD>\n\t\t<TITLE>Web Sudoku - Billions of Free Sudoku Puzzles to Play Online</TITLE>\n\t\t<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">\n        <meta id = "mobileviewport" name="viewport" content="width=device-width, initial-scale=1">\n\t\t<LINK REL="stylesheet" TYPE="text/css" HREF="style26.css">\n\n\n\t\t<SCRIPT language="JavaScript"><!--\n\t\t\tvar w_c=1;\n\t\t\tvar w_s=0;\n\t\t\tvar e_m=0;\n\t\t\tvar m_c=\'<FONT COLOR=green><B>Back to the start, we go!</B></FONT>\';\n\t\t\tvar m_m=\'<FONT COLOR=red><B>You have made some mistakes, highlighted in red!</B></FONT>\';\n\t\t\tvar m_w=\'<FONT COLOR=purple><B>Something is not quite right in * of the cells!</B></FONT>\';\n\t\t\tvar m_i=\'<FONT COLOR=blue><B>Everything is OK, you still have * to go!</B></FONT>\';\n\t\t\tvar m_d=\'<B>Here is the puzzle. Good luck!</B>\';\n\t\t\tvar s_c=false;\n\t\t\tvar cheat=\'368947215745621983219583647192374568453869721876152394531496872624738159987215436\';\n\t\t\tvar p

In [8]:
    page.text

u'<HTML>\n<HEAD>\n<TITLE>Web Sudoku - Billions of Free Sudoku Puzzles to Play Online</TITLE>\n<META NAME="Description" CONTENT="Play unlimited Sudoku online from Easy to Evil. Compatible with all browsers, iPad and Android. Provider of Sudoku puzzles for newspapers and other publications.">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n<script language="JavaScript">\n    document.domain="websudoku.com";\n</script>\n</HEAD>\n<FRAMESET COLS="*" FRAMEBORDER="NO" FRAMESPACING="0" BORDER="0">\n<FRAME SRC="https://nine.websudoku.com/?set_id=610926282">\n</FRAMESET>\n<NOFRAMES>\nPlay Sudoku - the number placing game taking the world by storm.\n<P>\n<B>We also supply <A HREF="services.php">Sudoku puzzles</A> for newspapers, books, magazines, websites and more.</B>\n<P>\nWeb Sudoku &copy; 2020. Protected by Copyscape <A HREF="http://www.copyscape.com/">plagiarism checker</A>.\nBy <A HREF="http://www.gidgreen.com/">Gideon Greenspan</A> and Rachel Lee.\n<P>\nPlease play o

In [ ]:
`